// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import EditableController from "./editable_controller"
application.register("editable", EditableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationSearchController from "./location_search_controller"
application.register("location-search", LocationSearchController)

import LocationsearchController from "./locationsearch_controller"
application.register("locationsearch", LocationsearchController)

import MapboxController from "./mapbox_controller"
application.register("mapbox", MapboxController)

import ModalsController from "./modals_controller"
application.register("modals", ModalsController)

import TurbomodalController from "./turbomodal_controller"
application.register("turbomodal", TurbomodalController)

import VisitDialogController from "./visit_dialog_controller"
application.register("visit-dialog", VisitDialogController)
