// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditableController from "./editable_controller"
application.register("editable", EditableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationSearchController from "./location_search_controller"
application.register("location-search", LocationSearchController)

import LocationsearchController from "./locationsearch_controller"
application.register("locationsearch", LocationsearchController)
